# .github/workflows/run-duffle.yml
name: Run Duffle on Push

on:
  workflow_dispatch:  # ðŸ‘ˆ This enables manual runs from GitHub UI
    inputs:
      run_duffle:
        description: 'Run Duffle tests'
        required: false
        default: true
        type: boolean
      run_smooth:
        description: 'Run Smooth tests'
        required: false
        default: true
        type: boolean
      run_unit_tests:
        description: 'Run unit tests'
        required: false
        default: true
        type: boolean

jobs:
  run-duffle:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.run_duffle }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Optional: only if you use a requirements file
          pip install .

      - name: Run Duffle.py
        run: python ./tests/Duffle.py

  run-smooth:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.run_smooth }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Optional: only if you use a requirements file
          pip install .

      - name: Run Duffle.py
        run: python ./tests/Smooth.py
  unit_tests:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.run_unit_tests }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Optional: only if you use a requirements file
          pip install .
          pip install pytest pytest-cov

      - name: Run unit tests
        run: |
          pytest unit_tests/